### ISSUE TITLE
Изменение фидбека по студенту

### ISSUE THREAD

**Issue by Dub4ek** [rolling-scopes-school/mentoring#10]
студента с логином avbutlov

Отказалась от студента (т.к. набрала студентов и больше не могу взять), но указала в фидбеке  "no" вместо "no, but good student". Можно ли поправить этот момент, чтобы студент мог попасть на перераспределение?

Это сообщение от ментора Ольги Сенюшкиной(Olga Seniushkina)

**Comment by dzmitry-varabei** [comment]
Привет! 
Этот параметр не влияет на перераспределение и если будут новые ментора они смогут его добрать
