### ISSUE TITLE
Add students to interview tab

### ISSUE THREAD

**Issue by valeraGorobets** [rolling-scopes-school/mentoring#6]
2 students that I chose to mentor do not appear in interview tab. My Github: https://github.com/valeraGorobets
Students:
Nastassia Zharnasek Github: nastassiazhernosek
ALENA FIODARAVA Github: elenafiodorova

**Comment by dbuhara** [comment]
1 student that I chose to mentor do not appear in interview tab. My Github: https://github.com/dbuhara
Student:
Irina Selivanova Github: bordo951

**Comment by VorobeyKirill** [comment]
1 student that I chose to mentor do not appear in interview tab. My Github: https://github.com/VorobeyKirill
Student:
Maksim Dashkevich, Github: maxdashkevich

**Comment by dzmitry-varabei** [comment]
@valeraGorobets @VorobeyKirill fixed!
